contacts/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path

from . import views

app_name = 'contacts'
urlpatterns = [
    path('', login_required(views.ContactList.as_view()), name='contacts_list'),
]

news/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path

from . import views

app_name = 'news'
urlpatterns = [
   path('', login_required(views.ListNews.as_view()), name='news_list'),
]

task_list/urls.py
from django.contrib import admin
from django.contrib.auth.decorators import login_required
from django.urls import path, include


from todo import views

urlpatterns = [
    path('admin/', admin.site.urls),

    # Auth
    path('signup/', views.Registration.as_view(), name='signupuser'),
    path('login/', views.LoginUser.as_view(), name='loginuser'),
    path('logout/', views.LogoutUser.as_view(), name='logoutuser'),

    # Todos
    path('', login_required(views.HomePage.as_view()), name='home'),
    path('tasks/', include('todo.urls')),
    path('contacts/', include('contacts.urls')),
    path('news/', include('news.urls')),
    path('bug_reports/', include('bug_reports.urls')),
]

todo/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path

from . import views

app_name = 'todo'
urlpatterns = [
    path('', login_required(views.TaskList.as_view()), name='tasks_list'),
    path('create/', login_required(views.NewTask.as_view()), name='create_task'),
    path('<int:pk>/', login_required(views.TaskDetail.as_view()), name='current_task'),
    path('<int:pk>/completed/', login_required(views.TaskComplete.as_view()), name='tasks_complete'),
    path('<int:pk>/delete/', login_required(views.TaskDelete.as_view()), name='tasks_delete'),
]

todo/models.py
from django.db import models
from django.contrib.auth.models import User


class Tasks(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=250)
    description = models.TextField(blank=True)
    created = models.DateTimeField(auto_now_add=True)

    completed = models.BooleanField(default=False)
    date_completed = models.DateTimeField(null=True, blank=True)

    important = models.BooleanField(default=False)

    class Meta:
        verbose_name = 'Задача'
        verbose_name_plural = 'Задачи'
        ordering = (
            'completed',
            'created',
        )

    def __str__(self):
        return f'{self.created}: {self.title}'

todo/forms.py
from django.forms import ModelForm, TextInput

from todo.models import Tasks


class TaskForm(ModelForm):
    class Meta:
        model = Tasks
        fields = (
            'user',
            'title',
            # 'description',
            # 'date_completed',
            # 'important',
        )

        widgets = {
            'title': TextInput(attrs={'class': 'form-control'}),
            # 'description': TextInput(attrs={'class': 'form-control'}),
        }

todo/views.py
from django.db import IntegrityError
from django.forms import model_to_dict
from django.http import HttpResponse, Http404, JsonResponse
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.views.generic import View
from rest_framework import status
from rest_framework.response import Response
from rest_framework.views import APIView
from django.contrib.auth.models import User
from django.contrib.auth import login, logout, authenticate
from rest_framework.viewsets import ViewSetMixin

from .forms import TaskForm

from todo.models import Tasks
from .serializers import TaskSerializer


class HomePage(APIView):

    def get(self, request):
        return render(request, 'todo/home.html', status=status.HTTP_200_OK)


class Registration(APIView):
    def get(self, request):
        context = {
            'form': UserCreationForm()
        }
        return render(request, 'todo/signupuser.html', context)

    def post(self, request):
        if request.POST['password1'] == request.POST['password2']:
            try:
                user = User.objects.create_user(request.POST['username'], password=request.POST['password1'])
                user.save()
                login(request, user)
                return redirect('home')
            except IntegrityError:
                context = {
                    'form': UserCreationForm(),
                    'error': 'Это имя пользователя уже используется.'
                }
                return render(request, 'todo/signupuser.html', context)

        else:
            context = {
                'form': UserCreationForm(),
                'error': 'Пароли не совпадают!'
            }
            return render(request, 'todo/signupuser.html', context)


class LoginUser(APIView):

    def get(self, request):
        context = {
            'form': AuthenticationForm()
        }
        return render(request, 'todo/loginuser.html', context, status=status.HTTP_200_OK)

    def post(self, request):
        user = authenticate(request, username=request.POST['username'], password=request.POST['password'])
        if not user:
            context = {
                'form': AuthenticationForm(),
                'error': 'Логин или пароль не совпадают.'
            }
            return render(request, 'todo/loginuser.html', context, status=status.HTTP_401_UNAUTHORIZED)
        else:
            try:
                login(request, user)
                return redirect('home')
            except IntegrityError:
                context = {
                    'error': 'Это имя пользователя уже используется.'
                }
                return render(request, 'todo/loginuser.html', context, status=status.HTTP_200_OK)


class LogoutUser(APIView):

    def get(self, request):
        logout(request)
        return redirect('loginuser')

    def post(self, request):
        logout(request)
        return redirect('loginuser')


class TaskList(View):
    """
    Список всех задач
    """

    def get(self, request):
        form = TaskForm()
        tasks = Tasks.objects.filter(user=request.user).all()
        serializer = TaskSerializer(tasks, many=True)
        context = {
            'form': form,
            'tasks': serializer.data
        }
        return render(request, 'todo/task_list.html', context)

    def post(self, request):
        form = TaskForm(request.POST)

        if form.is_valid():
            new_task = form.save()
            return JsonResponse(
                {
                    'task': model_to_dict(new_task),
                },
                status=200
            )
        else:
            return redirect('todo:tasks_list')


class NewTask(APIView):
    """
    Новая задача
    """

    def get(self, request):
        serializer = TaskSerializer()
        context = {
            'user': request.user,
            'form': TaskForm(serializer.data),
        }
        return render(request, 'todo/create_task.html', context)

    def post(self, request, *args, **kwargs):
        serializer = TaskSerializer(data=request.data)
        if serializer.is_valid():
            serializer.save()
            context = {
                'form': TaskForm(serializer.data),
            }
            return render(request, 'todo/create_task.html', context)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)


class TaskDetail(APIView):

    def get_object(self, pk, user):
        try:
            return Tasks.objects.get(pk=pk, user=user)
        except Tasks.DoesNotExist:
            return None

    def get(self, request, pk, format=None):
        task = self.get_object(pk, user=request.user)
        if task is None:
            return HttpResponse('Not found: 404')
        serializer = TaskSerializer(task)
        context = {
            'user': request.user,
            'form': TaskForm(serializer.data),
        }
        return render(request, 'todo/edit_task.html', context)

    def post(self, request, *args, **kwargs):
        task = self.get_object(kwargs['pk'])
        serializer = TaskSerializer(task, data=request.data)
        if serializer.is_valid():
            serializer.save()
            context = {
                'form': TaskForm(serializer.data),
            }
            return render(request, 'todo/edit_task.html', context)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

    def put(self, request, pk, format=None):
        task = self.get_object(pk)
        serializer = TaskSerializer(task, data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

    def delete(self, request, pk, format=None):
        task = self.get_object(pk)
        task.delete()
        return Response(status=status.HTTP_204_NO_CONTENT)


class TaskComplete(View):

    def post(self, request, pk):
        task = Tasks.objects.get(id=pk)
        task.completed = True
        task.save()
        return JsonResponse(
            {
                'task': model_to_dict(task)
            },
            status=200
        )


class TaskDelete(View):

    def post(self, request, pk):
        task = Tasks.objects.get(id=pk)
        task.delete()
        return JsonResponse(
            {
                'result': 'ok',
            },
            status=200
        )

todo/templates/todo/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <link rel="stylesheet" href="{% static 'lesson_topics/css/style.css' %}">
    <script src="{% static 'todo/js/script.js' %}"></script>

    <title>{% block title %}{% endblock %}</title>
</head>
<body>
<!--  Шапка сайта  -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark sticky-top">
        <div class="container-fluid">
            <a href="#" class="navbar-brand">
                <img src="{% static 'todo/img/TD_logo.png' %}" width="100" height="60" alt="Мои задачи">
            </a>
            <a href="#" class="navbar-brand">
                <img src="https://nuxtjs.org/logos/nuxt-square-white.svg" width="30" height="30" alt="Мои задачи">
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse"
                    data-target="#navbarSupportedContent"
                    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">

                <!--     главное меню       -->
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item active">
                        <a href="{% url 'home' %}" class="nav-link">Главная</a>
                    </li>
                    <li class="nav-item active">
                        <a href="{% url 'todo:tasks_list' %}" class="nav-link">Задачи</a>
                    </li>
                    <li class="nav-item">
                        <a href="{% url 'news:news_list' %}" class="nav-link">Новости</a>
                    </li>
                    <li class="nav-item">
                        <a href="{% url 'contacts:contacts_list' %}" class="nav-link">Контакты</a>
                    </li>
                </ul>

                <!--     поле для поиска       -->
                <form class="d-flex my-2 my-lg-0">
                    <input class="form-control me-2" type="search" placeholder="Поиск" aria-label="Поиск">
                    <button class="btn btn-outline-success me-2" type="submit">Поиск</button>
                </form>

                <!--     кнопка регистрации, авторизации и выхода       -->
                {% if user.is_authenticated %}
                    <div class="light me-2">
                        <b>Выполнен вход как: {{ user.username }}</b>
                    </div>
                    {% csrf_token %}
                    <a href="{% url 'logoutuser' %}" class="btn btn-outline-light mr-2">{{ user.username }}: Выход</a>
                {% else %}
                    <a href="{% url 'loginuser' %}" class="btn btn-outline-light me-2">Вход</a>
                    <a href="{% url 'signupuser' %}" class="btn btn-outline-light me-2">Регистрация</a>
                {% endif %}

            </div>
        </div>
    </nav>

    {% block header %}{% endblock %}

    <div class="content">
         {% block content %}{% endblock %}
    </div>

    {% block pagination %}{% endblock %}

    {% include './block/footer.html' %}


    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

</body>
</html>

todo/templates/todo/create_task.html
{% extends 'todo/base.html' %}

{% block content %}


<h1>Создание</h1>
<h2>{{ error }}</h2>
<form method="POST">

    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Сохранить</button>

</form>

{% endblock %}

todo/templates/todo/current_tasks_list.html
{% extends 'todo/base.html' %}
{% load static %}

{% block title %}Список всех задач{% endblock %}
{% block content %}
<h1>Список текущих задач</h1>

<ul>
    {% for task in tasks %}
    <li><a href="{% url 'todo:current_task' task.id %}">
        {% if task.important %}<b>{% endif %}
        {{ task.title }}
        {% if task.important %}</b>{% endif %}
        </a>
        {% if task.description %} - {{ task.description }} {% endif %}
    </li>
    {% endfor %}
</ul>

{% endblock %}

todo/templates/todo/edit_task.html
{% extends 'todo/base.html' %}

{% block content %}


<h1>Редактирование задачи</h1>
<h2>{{ error }}</h2>
<form method="POST">

    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Сохранить</button>

</form>

{% endblock %}

todo/templates/todo/home.html
{% extends 'todo/base.html' %}
{% load static %}

{% block title %}Мои задачи{% endblock %}

{% block content %}
<h1>Здесь планируется показ важных и просроченных задач и новостей</h1>

{% endblock %}

todo/templates/todo/loginuser.html
{% extends 'todo/base.html' %}

{% block content %}


<h1>Вход</h1>
<h2>{{ error }}</h2>
<form method="POST">

    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Войти</button>

</form>

{% endblock %}

todo/templates/todo/signupuser.html
<h1>Регистрация</h1>
<h2>{{ error }}</h2>
<form method="POST">

    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Зарегистрироваться</button>

</form>

todo/templates/todo/task_list.html
{% extends 'base.html' %}

{% block title %}
    TEXT
{% endblock %}


{% block content %}

    <div class="col-8 mt-5">
        <form class="" id="createTaskForm" method="post" data-url="{% url 'todo:tasks_list' %}">
<!--            <div class="">-->
            {% csrf_token %}
            <div class="d-flex flex-row mb-3">
                {% for field in form %}
                <div class="">
                    {{ field }}
                </div>
            {% endfor %}

            <button type="button" class="btn btn-outline-success mx-3" id="createButton">Create</button>
<!--            </div>-->
        </form>
    </div>

    <div class="mt-5" id="taskList">
        {% for task in tasks %}
        <div class="card mb-1" id="taskCard" data-id="{{ task.id }}"
             style="{% if task.completed %} text-decoration: line-through; {% endif %}">
            <div class="row g-0">
            <div class="card-body  mb-0">
                <div class="d-flex flex-row align-middle">
                    <div class="align-middle">
                        {{task.completed}} | {{ task.title }}
                        <button type="button" class="close float-right" data-id="{{ task.id }}"><span aria-hidden="true">&times;</span> </button>
                    </div>
                </div>
            </div>
            </div>
        </div>
        {% endfor %}
    </div>

{% endblock %}